### ISSUE TITLE
Implement STM SPI interface

### ISSUE THREAD

**Issue by khuehm17** [khuehm17/AD7606-DAQ#3]
Implement SPI interface on STM32F4 with DMA (Direct Memory Access).
For testing function, can use another arduino or ESP.

**Comment by hphnngcquan** [comment]
SPI Implementation Completed
Updates: SPI1 Mode changed to Rx Only, DMA Mode changed to Normal
Notation: Master_Rx cannot use DMA Circular Mode (According to HAL_SPI Procedures)
@khuehm17
